spring:
  boot:
    admin:
      ui:
        remember-me-enabled: false
      instance-auth:
        enabled: true 
        service-map:
          spring-boot-admin-example: 
            user-name: ${spring.security.user.name}
            user-password: ${spring.security.user.password}
  security:
    user:  # username password need to be replaced from config map
      name: changeit # SPRING_SECURITY_USER_NAME
      password: changeit # SPRING_SECURITY_USER_PASSWORD
  jmx:
    enabled: true # sba client

management:
  endpoints:
    web:
      exposure:
        include: "*" # sba client

---
# activate this profile when you want to try connecting to ocp from your local to test discovery mechanism.
spring:
  config:
    activate:
      on-profile:
        - local
  cloud:
    kubernetes:
      client:
        master-url: https://api.server.address:6443
        oauth-token: the-token