spring:
  boot:
    admin:
      discovery:
        services:
        - todo-list
        - spring-boot-admin-example
#  cloud:
#    kubernetes:
#      discovery:
#        all-namespaces: true # discover services in any namespace, need --all-namespaces permission
#        service-labels: # label filters
#          spring-boot: true
#          env: sandbox
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
# activate this profile on all non-local environment, for example, dev, uat, prd
# we need to disable all db change management solution, spring natvie, liquibase, when deploying non local environment.
# It is the CICD pipeline will execute the liquibase before code deployment.
spring:
  config:
    activate:
      on-profile:
        - local
  cloud:
    kubernetes:
      client:
        master-url: https://api.rm2.thpm.p1.openshiftapps.com:6443
        oauth-token: sha256~jXRG22OVXR-V8a1pB6_nSfGpCPOlJC30k44u_xqUtIs
        namespace: shawn-yang-ibm-dev